# Generated by Django 4.1.7 on 2023-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_langusge_movie_language_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie.jpg', upload_to='movies'),
        ),
    ]
